<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Misiu.Kestrel.Transport.Amqp\Misiu.Kestrel.Transport.Amqp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    </ItemGroup>

</Project>
